name: dnsmasq
base: core24
adopt-info: dnsmasq
summary: Small caching DNS proxy and DHCP/TFTP server
description: |
  Dnsmasq is a lightweight, easy to configure, DNS forwarder and DHCP
  server. It is designed to provide DNS and optionally, DHCP, to a
  small network. It can serve the names of local machines which are
  not in the global DNS. The DHCP server integrates with the DNS
  server and allows machines with DHCP-allocated addresses
  to appear in the DNS with names configured either in each host or
  in a central configuration file. Dnsmasq supports static and dynamic
  DHCP leases and BOOTP/TFTP for network booting of diskless machines.
  .
  This snap only operates as DHCP server, DNS support is disabled

grade: stable
confinement: strict

apps:
  dnsmasq:
    command: usr/sbin/dnsmasq -k -p0 -x$SNAP_COMMON/dnsmasq.pid -C$SNAP_DATA/dnsmasq.conf -u root -g snap_daemon
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe
      - network-setup-observe

system-usernames:
  snap_daemon: shared

parts:
  dnsmasq:
    plugin: dump
    source: .
    stage-packages:
      - dnsmasq
    override-prime: |
      craftctl default
      VER="$(zcat usr/share/doc/dnsmasq/changelog.Debian.gz | head -1 | sed 's/^.*(//;s/-.*$//')"
      craftctl set version="2.90"
